services:
  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
    environment:
      - LDAP_ORGANISATION=My Awesome Inc.
      - LDAP_DOMAIN=example.com
      - LDAP_ADMIN_PASSWORD=mysecretpassword
    networks:
      - ldap-net
  phpadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: phpldapadmin
    ports:
      - "6443:443"
      - "6080:80"
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
      - PHPLDAPADMIN_HTTPS=false
    depends_on:
      - openldap
    networks:
      - ldap-net

volumes:
  ldap_data:
    driver: local
  ldap_config:
    driver: local

networks:
  ldap-net: