services:
  db:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=myappdb
      - POSTGRES_USER=myappuser
      - POSTGRES_PASSWORD=myappsecret
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U myappuser -d myappdb" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "3000:8080"

volumes:
  postgres-data:
