logging:
  level:
    org.springframework.security: DEBUG

spring:
  application:
    name: spring-security-in-action-demo
  datasource:
    url: jdbc:postgresql://db:5432/myappdb
    username: myappuser
    password: myappsecret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
